spring.application.name=user-service
server.port=8081

# ================= DB =================
#spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= EUREKA =================
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Optional but recommended
eureka.instance.prefer-ip-address=true

