spring.application.name=order-service

server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ================= EUREKA =================
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#eureka.instance.hostname=ORDER-service
eureka.instance.prefer-ip-address=true